### ISSUE TITLE
Parsing failure with current vk.xml

### ISSUE THREAD

**Issue by tari3x** [Octachron/olivine#5]
I wonder if it makes sense to include a fixed copy of vk.xml with this package?

```
./bin/libgen spec/vk.xml lib
 Parsing failure typedef :
struct⦗ANativeWindow⦘;
```

**Comment by tari3x** [comment]
I might be interested in spending some effort to get it to work. Let me know if you have any thoughts on how hard it would be.

**Comment by Octachron** [comment]
The parsing failure is gone (well, I have ignored the Objective-C fragment for now), but the xml extractor needs now to understand deprecated aliases. This is the problem with the vulkan spec which is still in flux and at best pretends to be written in xml.

**Comment by tari3x** [comment]
Cool, thanks, I'll try this again!
